// Automatically generated by astro-icon
// 15a6b87f94d055779ce5d25a413ebbe901f162f048c5982dbc3b10eacdc117c3

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ph:arrow-right"
		| "ph:briefcase-duotone"
		| "ph:caret-down"
		| "ph:chart-bar-duotone"
		| "ph:chat-circle-dots"
		| "ph:check"
		| "ph:clipboard"
		| "ph:eye"
		| "ph:eye-slash"
		| "ph:file-text-duotone"
		| "ph:info"
		| "ph:linkedin-logo"
		| "ph:list"
		| "ph:map-pin"
		| "ph:minus"
		| "ph:moon"
		| "ph:mouse-scroll"
		| "ph:path-duotone"
		| "ph:plus"
		| "ph:question"
		| "ph:seal-check-duotone"
		| "ph:shield-check-duotone"
		| "ph:sun"
		| "ph:target-duotone"
		| "ph:warning"
		| "ph:warning-circle"
		| "ph:warning-duotone"
		| "ph:x";
}